name: Daimler Trucks
on:
  push:
    branches:
      - staging
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: master
      uses: appleboy/ssh-action@v0.1.6
      if: github.ref == 'refs/heads/master'
      with:
        host: ${{ secrets.PROD_CICD_HOST }}
        username: ${{ secrets.PROD_CICD_USERNAME }}
        key: ${{ secrets.CICD_KEY }}
        port: ${{ secrets.CICD_PORT }}
        script: |
          whoami
          cd ${{ secrets.PROD_PATH }} && git pull https://${{ secrets.CICD_TOKEN }}:${{ secrets.CICD_TOKEN }}@${{ secrets.GIT_URL }} master
    - name: staging
      uses: appleboy/ssh-action@v0.1.6
      if: github.ref == 'refs/heads/staging'
      with:
        host: ${{ secrets.STAG_CICD_HOST }}
        username: ${{ secrets.STAG_CICD_USERNAME }}
        key: ${{ secrets.CICD_KEY }}
        port: ${{ secrets.CICD_PORT }}
        script: |
          whoami
          cd ${{ secrets.STAG_PATH }} && git pull https://${{ secrets.CICD_TOKEN }}:${{ secrets.CICD_TOKEN }}@${{ secrets.GIT_URL }} staging
